/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from CardSide.djinni

#import <Foundation/Foundation.h>
@class CardSide;
@class Background;
@class Picture;
@class Text;
@class Background;
@class CardSide;
@class Picture;
@class Text;

extern int8_t const CardSide_BACKGROUND_TAG;
extern int8_t const CardSide_PICTURE_TAG;
extern int8_t const CardSide_CARD_ELEMENTS_TAG;
extern int8_t const CardSide_ALWAYS_TEXT_TAG;
extern int8_t const CardSide_PIN_TEXT_TAG;
extern int8_t const CardSide_NO_PIN_TEXT_TAG;

/** Auto-generated Djinni interface for ::mpsdk::utils::payment_cld::CardSide_t */
@interface CardSide : NSObject

- (id _Nonnull)initWithTypeAndData:(uint8_t)type cardSideData:(NSData* _Nonnull)cardSideData cardSideOffset:(int32_t)cardSideOffset cardSideLength:(int32_t)cardSideLength;

- (id _Nonnull)initWithType:(uint8_t)type;

+ (CardSide* _Nonnull)createWithType:(uint8_t)type;

+ (CardSide* _Nonnull)createWithTypeAndData:(uint8_t)type
                                          cardSideData:(NSData* _Nonnull)cardSideData
                                        cardSideOffset:(int32_t)cardSideOffset
                                        cardSideLength:(int32_t)cardSideLength;

- (void)updateCardSideContent:(NSData* _Nonnull)cardSideData
               cardSideOffset:(int32_t)cardSideOffset
               cardSideLength:(int32_t)cardSideLength;

- (Background* _Nonnull)getCardBackground;

- (int16_t)getCardElements;

- (NSArray<Picture*>* _Nonnull)getPictureList;

- (NSArray<Text*>* _Nonnull)getText;

- (void)clear;

@end
