/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from CredentialsReplenishmentPolicy.djinni

#import <Foundation/Foundation.h>
@protocol Card;
@protocol Card;


/**
 * Auto-generated Djinni interface for ::mpsdk::componentinterface::CredentialsReplenishmentPolicy_t
 * 
 * Interface to allow for custom key management policies.
 * 
 */
@protocol CredentialsReplenishmentPolicy

/**
 * 
 * Decide whether new credentials should be requested for the provided card.<br>
 * This method is called each time after a credential has been used, as well as application
 * startup.
 * 
 * @param card Instance of {@link Card_t} to determine if
 * we should request new credentials for.
 * @return true if more credentials should be requested; otherwise false.
 * 
 * 
 */
- (BOOL)shouldRequestNewCredentials:(id<Card> _Nonnull)card;

@end
