/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DatabaseUpgradeCrypto.djinni

#import <Foundation/Foundation.h>
@class LocalDekEncryptedData;
@class RMKekEncryptedData;
@class LocalDekEncryptedData;
@class RMKekEncryptedData;


/**
 * Auto-generated Djinni interface for ::mpsdk::componentinterface::crypto::DatabaseUpgradeCrypto_t
 * 
 * Provides an interface for the Database module to encrypt / unencrypt data
 * 
 */
@protocol DatabaseUpgradeCrypto

/**
 * 
 * Encrypt data with the current database key so it is ready to be stored
 * 
 * @param dataToBeEncrypted Data to be encrypted
 * @return Data protected with the Local DEK
 * @exception GeneralSecurityException If something goes wrong inside crypto engine
 * 
 * 
 */
- (LocalDekEncryptedData* _Nullable)encryptDataUsingLocalDekKey:(NSData* _Nonnull)dataToBeEncrypted error:(NSError* _Nullable __autoreleasing * _Nullable)error;

/**
 * 
 * Encrypt data with the current database key so it is ready to be stored
 * 
 * @param dataToBeEncrypted Data to be encrypted
 * @return Data protected with Remote Key Encryption Key (RM KEK)
 * @exception GeneralSecurityException If something goes wrong inside crypto engine
 * 
 * 
 */
- (RMKekEncryptedData* _Nullable)encryptDataUsingRemoteKekKey:(NSData* _Nonnull)dataToBeEncrypted error:(NSError* _Nullable __autoreleasing * _Nullable)error;

@end
