/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DatabaseInitParams.djinni

#import <Foundation/Foundation.h>


/**
 * Auto-generated Djinni interface for ::mpsdk::componentinterface::database::DatabaseInitParams_t
 * 
 * Encapsulate the parameter which are either required or optional for LDE initialization.
 * 
 */
@protocol DatabaseInitParams

/**
 * 
 * @return True if the required parameters (CmsMpaId and DeviceFingerprint) are provided,
 * false otherwise
 * 
 * 
 */
- (BOOL)isValid;

/**
 * 
 * @return CMS MPA identifier.
 * 
 * 
 */
- (NSData* _Nonnull)getCmsMpaId;

/**
 * 
 * @return Remote management url provided by CMS-D.
 * 
 * 
 */
- (NSString* _Nonnull)getUrlRemoteManagement;

/**
 * 
 * Configure the remote management url provided by CMS-D
 * 
 * @param urlRemoteManagement Provided by CMS-D
 * 
 * 
 */
- (void)setUrlRemoteManagement:(NSString* _Nonnull)urlRemoteManagement;

/**
 * 
 * @return Mobile device finger print
 * 
 * 
 */
- (NSData* _Nonnull)getMpaFingerPrint;

/**
 * 
 * @return RNS MPA identifier.
 * 
 * 
 */
- (NSData* _Nonnull)getRnsMpaId;

/**
 * 
 * Configure the RNS MPA identifier.
 * 
 * 
 * 
 */
- (void)setRnsMpaId:(NSData* _Nonnull)rnsMpaId;

@end
