/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DsrpOutput.djinni

#import "mpsdk_componentinterface/RemoteCryptogramType.h"
#import "mpsdk_componentinterface/RemoteCryptogramType.h"
#import <Foundation/Foundation.h>


/** Auto-generated Djinni interface for ::mpsdk::componentinterface::DsrpOutput_t */
@protocol DsrpOutput

/**
 * 
 * Retrieve the transaction cryptogram data
 * 
 * @return the transaction cryptogram data
 * 
 * 
 */
- (NSData* _Nonnull)getTransactionCryptogramData;

/**
 * 
 * Retrieve the PAN number
 * 
 * @return the PAN number
 * 
 * 
 */
- (NSString* _Nonnull)getPan;

/**
 * 
 * Retrieve the PAN sequence number
 * 
 * @return the PAN sequence number
 * 
 * 
 */
- (int32_t)getPanSequenceNumber;

/**
 * 
 * Retrieve the Cryptogram Type
 * 
 * @return the Cryptogram Type
 * 
 * 
 */
- (RemoteCryptogramType)getCryptogramType;

/**
 * 
 * Retrieve the Track 2 Data
 * 
 * @return the Track 2 Data
 * 
 * 
 */
- (NSString* _Nonnull)getTrack2Data;

/**
 * 
 * Retrieve the Payment Account Reference
 * 
 * @return the PAR
 * 
 * 
 */
- (NSData* _Nonnull)getPar;

/**
 * 
 * Retrieve the Expury Date of the card
 * 
 * @return the Expiry Date (YYMMDD)
 * 
 * 
 */
- (NSString* _Nonnull)getExpirationDate;

/**
 * 
 * Retrieve the Transaction id for the transaction
 * 
 * @return the transaction id
 * 
 * 
 */
- (NSData* _Nonnull)getTransactionId;

@end
