/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DsrpData.djinni

#import "mpsdk_componentinterface/CardCvmModel.h"
#import "mpsdk_componentinterface/CardUcafVersion.h"
#import "mpsdk_componentinterface/CardUmdConfig.h"
#import "mpsdk_componentinterface/CardUcafVersion.h"
#import "mpsdk_componentinterface/CardUmdConfig.h"
#import "mpsdk_componentinterface/CardCvmModel.h"
#import <Foundation/Foundation.h>


/** Auto-generated Djinni interface for ::mpsdk::componentinterface::DsrpData_t */
@protocol DsrpData

- (NSData* _Nonnull)getAip;

- (NSData* _Nonnull)getExpiryDate;

- (NSData* _Nonnull)getPanSequenceNumber;

- (NSData* _Nonnull)getTrack2EquivalentData;

- (NSData* _Nonnull)getIssuerApplicationData;

- (CardCvmModel)getCvmModel;

- (CardUmdConfig)getUmdGeneration;

- (CardUcafVersion)getUcafVersion;

- (NSData* _Nullable)getPar;

- (NSData* _Nullable)getCiacDecline;

- (NSData* _Nullable)getCvrMaskAnd;

@end
