/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DuplicateTransactionCredential.djinni

#import <Foundation/Foundation.h>



#import "mpsdk_componentinterface/LdeUncheckedException.h"

/**
 * Auto-generated Djinni interface for ::mpsdk::componentinterface::database::exception::DuplicateTransactionCredential_t
 * 
 * Exception_t when a transaction credential with the same card_id and atc is being added into the
 * database
 * 
 */
@interface DuplicateTransactionCredential : LdeUncheckedException

- (id _Nonnull)initWithTokenUniqueReference:(NSString* _Nonnull)tokenUniqueReference atc:(signed int)atc reason:(NSString* _Nonnull)reason;

- (id _Nonnull)init;

/**
 * 
 * Retrieve the token unique reference of the transaction credential that already exists
 * 
 * 
 */
- (NSString* _Nullable)getTokenUniqueReference;

/**
 * 
 * Retrieve the Application Transaction Counter of the transaction credential that already
 * exists
 * 
 * 
 */
- (int32_t)getAtc;

@end
