/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EmptyMcbpLogger.djinni

#import <Foundation/Foundation.h>
@class Exception;
@class Exception;



#import "mpsdk_componentinterface/McbpLogger.h"

/** Auto-generated Djinni interface for ::mpsdk::utils::log::EmptyMcbpLogger_t */
@interface EmptyMcbpLogger : NSObject<McbpLogger>

- (id _Nonnull)init;

- (void)d:(NSString* _Nonnull)message;

- (void)ex:(Exception* _Nonnull)exception
   message:(NSString* _Nonnull)message;

- (void)e:(NSString* _Nonnull)message;

- (void)i:(NSString* _Nonnull)message;

- (void)v:(NSString* _Nonnull)message;

- (void)w:(NSString* _Nonnull)message;

@end
