/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from HttpResponseStatus.djinni

#import <Foundation/Foundation.h>

/**
 * Auto-generated Djinni interface for ::mpsdk::componentinterface::http::HttpResponseStatus_t
 * 
 * Status Codes (copied from Apache Http Status)
 * 
 * 
 * 
 */
typedef NS_ENUM(NSInteger, HttpResponseStatus)
{
    HttpResponseStatus_CONTINUE = 100,
    HttpResponseStatus_SWITCHING_PROTOCOLS = 101,
    HttpResponseStatus_PROCESSING = 102,
    HttpResponseStatus_OK = 200,
    HttpResponseStatus_CREATED = 201,
    HttpResponseStatus_ACCEPTED = 202,
    HttpResponseStatus_NON_AUTHORITATIVE_INFORMATION = 203,
    HttpResponseStatus_NO_CONTENT = 204,
    HttpResponseStatus_RESET_CONTENT = 205,
    HttpResponseStatus_PARTIAL_CONTENT = 206,
    HttpResponseStatus_MULTI_STATUS = 207,
    HttpResponseStatus_MULTIPLE_CHOICES = 300,
    HttpResponseStatus_MOVED_PERMANENTLY = 301,
    HttpResponseStatus_MOVED_TEMPORARILY = 302,
    HttpResponseStatus_SEE_OTHER = 303,
    HttpResponseStatus_NOT_MODIFIED = 304,
    HttpResponseStatus_USE_PROXY = 305,
    HttpResponseStatus_TEMPORARY_REDIRECT = 307,
    HttpResponseStatus_BAD_REQUEST = 400,
    HttpResponseStatus_UNAUTHORIZED = 401,
    HttpResponseStatus_PAYMENT_REQUIRED = 402,
    HttpResponseStatus_FORBIDDEN = 403,
    HttpResponseStatus_NOT_FOUND = 404,
    HttpResponseStatus_METHOD_NOT_ALLOWED = 405,
    HttpResponseStatus_NOT_ACCEPTABLE = 406,
    HttpResponseStatus_PROXY_AUTHENTICATION_REQUIRED = 407,
    HttpResponseStatus_REQUEST_TIMEOUT = 408,
    HttpResponseStatus_CONFLICT = 409,
    HttpResponseStatus_GONE = 410,
    HttpResponseStatus_LENGTH_REQUIRED = 411,
    HttpResponseStatus_PRECONDITION_FAILED = 412,
    HttpResponseStatus_REQUEST_TOO_LONG = 413,
    HttpResponseStatus_REQUEST_URI_TOO_LONG = 414,
    HttpResponseStatus_UNSUPPORTED_MEDIA_TYPE = 415,
    HttpResponseStatus_REQUESTED_RANGE_NOT_SATISFIABLE = 416,
    HttpResponseStatus_EXPECTATION_FAILED = 417,
    HttpResponseStatus_INSUFFICIENT_SPACE_ON_RESOURCE = 419,
    HttpResponseStatus_METHOD_FAILURE = 420,
    HttpResponseStatus_UNPROCESSABLE_ENTITY = 422,
    HttpResponseStatus_LOCKED = 423,
    HttpResponseStatus_FAILED_DEPENDENCY = 424,
    HttpResponseStatus_INTERNAL_SERVER_ERROR = 500,
    HttpResponseStatus_NOT_IMPLEMENTED = 501,
    HttpResponseStatus_BAD_GATEWAY = 502,
    HttpResponseStatus_SERVICE_UNAVAILABLE = 503,
    HttpResponseStatus_GATEWAY_TIMEOUT = 504,
    HttpResponseStatus_HTTP_VERSION_NOT_SUPPORTED = 505,
    HttpResponseStatus_INSUFFICIENT_STORAGE = 507,
};
