/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from HttpException.djinni

#import <Foundation/Foundation.h>

extern int32_t const HttpException_UNKNOWN_HTTP_ERROR;
/**
 * 
 * Http timeout occurred
 * 
 */
extern int32_t const HttpException_HTTP_TIMEOUT_OCCURRED;
/**
 * 
 * Error occurred at SSL level while communication
 * 
 */
extern int32_t const HttpException_SSL_ERROR;
/**
 * 
 * Unknown error occurred while communication
 * 
 */
extern int32_t const HttpException_UNKNOWN_HTTP_ERROR_CODE;


#import "mpsdk_componentinterface/Exception.h"

/**
 * Auto-generated Djinni interface for ::mpsdk::componentinterface::http::HttpException_t
 * 
 * Custom exception for Http communication.
 * 
 */
@interface HttpException : Exception

- (id _Nonnull)initWithErrorCode:(signed int)errorCode errorMessage:(NSString* _Nonnull)errorMessage;

- (id _Nonnull)initWithErrorMessage:(NSString* _Nonnull)errorMessage;

- (id _Nonnull)init;

- (int32_t)getErrorCode;

- (NSString* _Nonnull)getErrorMessage;

@end
