/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from JSONArray.djinni

#import <Foundation/Foundation.h>
@class JSONArray;
@class JSONObject;
@class JSONArray;
@class JSONObject;


/**
 * Auto-generated Djinni interface for ::mpsdk::utils::json::JSONArray_t
 * 
 * Wraps the underlying used library in a representation that follows JSONArray from Android.
 * 
 * 
 */
@interface JSONArray : NSObject

- (id _Nonnull)initWithJsonString:(NSString* _Nonnull)json;

+ (JSONArray* _Nonnull)createWithJsonString:(NSString* _Nonnull)json;

- (NSString* _Nonnull)toString;

- (int32_t)length;

- (BOOL)isNull:(int32_t)index;

- (NSString* _Nullable)getString:(int32_t)index;

- (BOOL)getBoolean:(int32_t)index error:(NSError* _Nullable __autoreleasing * _Nullable)error;

- (double)getDouble:(int32_t)index error:(NSError* _Nullable __autoreleasing * _Nullable)error;

- (int32_t)getInt:(int32_t)index error:(NSError* _Nullable __autoreleasing * _Nullable)error;

- (int64_t)getLong:(int32_t)index error:(NSError* _Nullable __autoreleasing * _Nullable)error;

- (JSONObject* _Nullable)getJSONObject:(int32_t)index error:(NSError* _Nullable __autoreleasing * _Nullable)error;

- (JSONArray* _Nullable)getJSONArray:(int32_t)index error:(NSError* _Nullable __autoreleasing * _Nullable)error;

- (JSONArray* _Nonnull)appendString:(NSString* _Nullable)value;

- (JSONArray* _Nonnull)appendBoolean:(NSNumber* _Nullable)value;

- (JSONArray* _Nonnull)appendDouble:(NSNumber* _Nullable)value;

- (JSONArray* _Nonnull)appendInt:(NSNumber* _Nullable)value;

- (JSONArray* _Nonnull)appendLong:(NSNumber* _Nullable)value;

- (JSONArray* _Nonnull)appendObject:(JSONObject* _Nonnull)value;

- (JSONArray* _Nonnull)appendArray:(JSONArray* _Nonnull)value;

- (JSONArray* _Nonnull)insertString:(int32_t)index
                                         value:(NSString* _Nullable)value;

- (JSONArray* _Nonnull)insertBoolean:(int32_t)index
                                          value:(NSNumber* _Nullable)value;

- (JSONArray* _Nonnull)insertDouble:(int32_t)index
                                         value:(NSNumber* _Nullable)value;

- (JSONArray* _Nonnull)insertInt:(int32_t)index
                                      value:(NSNumber* _Nullable)value;

- (JSONArray* _Nonnull)insertLong:(int32_t)index
                                       value:(NSNumber* _Nullable)value;

- (JSONArray* _Nonnull)insertObject:(int32_t)index
                                         value:(JSONObject* _Nonnull)value;

- (JSONArray* _Nonnull)insertArray:(int32_t)index
                                        value:(JSONArray* _Nonnull)value;

@end
