/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from JSONObject.djinni

#import <Foundation/Foundation.h>
@class JSONObject;
@class JSONArray;
@class JSONArray;
@class JSONObject;


/**
 * Auto-generated Djinni interface for ::mpsdk::utils::json::JSONObject_t
 * 
 * Wraps the underlying used library in a representation that follows JSONObject from Android.
 * 
 * 
 */
@interface JSONObject : NSObject

- (id _Nonnull)initWithJsonString:(NSString* _Nonnull)json;

+ (JSONObject* _Nonnull)createWithJsonString:(NSString* _Nonnull)json;

- (NSString* _Nonnull)toString;

- (int32_t)length;

- (NSArray<NSString*>* _Nonnull)keys;

- (BOOL)has:(NSString* _Nonnull)key;

- (BOOL)isNull:(NSString* _Nonnull)key;

- (NSString* _Nullable)getString:(NSString* _Nonnull)key;

- (BOOL)getBoolean:(NSString* _Nonnull)key error:(NSError* _Nullable __autoreleasing * _Nullable)error;

- (double)getDouble:(NSString* _Nonnull)key error:(NSError* _Nullable __autoreleasing * _Nullable)error;

- (int32_t)getInt:(NSString* _Nonnull)key error:(NSError* _Nullable __autoreleasing * _Nullable)error;

- (int64_t)getLong:(NSString* _Nonnull)key error:(NSError* _Nullable __autoreleasing * _Nullable)error;

- (JSONObject* _Nullable)getJSONObject:(NSString* _Nonnull)key error:(NSError* _Nullable __autoreleasing * _Nullable)error;

- (JSONArray* _Nullable)getJSONArray:(NSString* _Nonnull)key error:(NSError* _Nullable __autoreleasing * _Nullable)error;

- (JSONObject* _Nonnull)putString:(NSString* _Nonnull)key
                                       value:(NSString* _Nullable)value;

- (JSONObject* _Nonnull)putBoolean:(NSString* _Nonnull)key
                                        value:(NSNumber* _Nullable)value;

- (JSONObject* _Nonnull)putDouble:(NSString* _Nonnull)key
                                       value:(NSNumber* _Nullable)value;

- (JSONObject* _Nonnull)putInt:(NSString* _Nonnull)key
                                    value:(NSNumber* _Nullable)value;

- (JSONObject* _Nonnull)putLong:(NSString* _Nonnull)key
                                     value:(NSNumber* _Nullable)value;

- (JSONObject* _Nonnull)putObject:(NSString* _Nonnull)key
                                       value:(JSONObject* _Nonnull)value;

- (JSONObject* _Nonnull)putArray:(NSString* _Nonnull)key
                                      value:(JSONArray* _Nonnull)value;

@end
