/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LogUtils.djinni

#import <Foundation/Foundation.h>
@class LogUtils;
@class Exception;
@class Exception;
@class LogUtils;


/** Auto-generated Djinni interface for ::mpsdk::utils::log::LogUtils_t */
@interface LogUtils : NSObject

+ (LogUtils* _Nonnull)getInstance:(NSString* _Nonnull)componentName;

/**
 * 
 * Add begin info log
 * 
 * @param logMessage message to log
 * 
 */
- (void)beginLog:(NSString* _Nonnull)logMessage;

/**
 * 
 * Add end info log
 * 
 * @param logMessage message to log
 * 
 */
- (void)endLog:(NSString* _Nonnull)logMessage;

/**
 * 
 * Add info log
 * 
 * @param logMessage message to log
 * 
 */
- (void)infoLog:(NSString* _Nonnull)logMessage;

/**
 * 
 * Add debug log
 * 
 * @param logMessage message to log
 * 
 */
- (void)debugLog:(NSString* _Nonnull)logMessage;

/**
 * 
 * Add error log
 * 
 * @param logMessage message to log
 * 
 */
- (void)errorLog:(NSString* _Nonnull)logMessage;

/**
 * 
 * Add error log
 * 
 * @param logMessage message to log
 * 
 */
- (void)exceptionLog:(Exception* _Nonnull)throwable
          logMessage:(NSString* _Nonnull)logMessage;

/**
 * 
 * Add verbose log
 * 
 * @param logMessage message to log
 * 
 */
- (void)verboseLog:(NSString* _Nonnull)logMessage;

/**
 * 
 * Add warning log
 * 
 * @param logMessage message to log
 * 
 */
- (void)warningLog:(NSString* _Nonnull)logMessage;

@end
