/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Picture.djinni

#import <Foundation/Foundation.h>
@class Picture;
@class Picture;


/** Auto-generated Djinni interface for ::mpsdk::utils::payment_cld::Picture_t */
@interface Picture : NSObject

- (id _Nonnull)initWithData:(NSData* _Nonnull)pictureData offset:(int32_t)offset length:(int32_t)length;

+ (Picture* _Nonnull)createWithData:(NSData* _Nonnull)pictureData
                                        offset:(int32_t)offset
                                        length:(int32_t)length;

- (uint8_t)getPictureHorizontalPosition;

- (uint8_t)getPictureVerticalPosition;

- (uint8_t)getPictureScale;

- (uint8_t)getPictureType;

- (NSData* _Nonnull)getPictureValue;

- (void)setPictureParams:(uint8_t)type
                   value:(NSData* _Nonnull)value
      horizontalPosition:(uint8_t)horizontalPosition
        verticalPosition:(uint8_t)verticalPosition
                   scale:(uint8_t)scale;

@end
