/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from PinDataProvider.djinni

#import <Foundation/Foundation.h>
@class WalletDekEncryptedData;
@class WalletDekEncryptedData;


/** Auto-generated Djinni interface for ::mpsdk::componentinterface::crypto::PinDataProvider_t */
@protocol PinDataProvider

/**
 * 
 * Get the current PIN that has been entered. Encrypted by W_DEK
 * 
 * @return the current PIN protected by W_DEK
 * 
 * 
 */
- (WalletDekEncryptedData* _Nullable)getEncryptedCurrentPin;

/**
 * 
 * Used during "Change PIN" operations to retrieve the new PIN. Encrypted by W_DEK
 * 
 * @return the new PIN protected by W_DEK
 * 
 * 
 */
- (WalletDekEncryptedData* _Nullable)getEncryptedNewPin;

/**
 * 
 * The Wallet may maintain a pseudo PIN and the real validation will be provided by fingerprint
 * or some other solution. The wallet will need to store this PIN and if there is a key rollover
 * a new value will be provided here
 * 
 * @param newKeyEncryptedMobilePin the pseudo mobile PIN, protected by the updated W_DEK
 * 
 * 
 */
- (void)onKeyRollover:(WalletDekEncryptedData* _Nonnull)newKeyEncryptedMobilePin;

@end
