/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from RegistrationRequestParameters.djinni

#import <Foundation/Foundation.h>
@class CmsDPublicKeyEncryptedData;
@class RgkEncryptedData;
@class CmsDPublicKeyEncryptedData;
@class RgkEncryptedData;


/**
 * Auto-generated Djinni interface for ::mpsdk::componentinterface::remotemanagement::RegistrationRequestParameters_t
 * 
 * Utility data structure to return the content of a registration request parameter
 * 
 * 
 * 
 */
@protocol RegistrationRequestParameters

/**
 * 
 * Get the Mobile Random Generated Key protected with the public key of the CMS-D
 * 
 * @return It can be null in case the mobile PIN was not given as an input
 * 
 * 
 */
- (CmsDPublicKeyEncryptedData* _Nullable)getRandomGeneratedKey;

/**
 * 
 * If not null, it contains the mobile pin block protected with the RGK
 * 
 * @return It can be null in case the mobile PIN was not given as an input
 * 
 * 
 */
- (RgkEncryptedData* _Nullable)getNewMobilePin;

@end
