/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from RemoteManagementException.djinni

#import <Foundation/Foundation.h>



#import "mpsdk_componentinterface/Exception.h"

/**
 * Auto-generated Djinni interface for ::mpsdk::componentinterface::remotemanagement::RemoteManagementException_t
 * 
 * Base class for all remote management exception types
 * 
 */
@interface RemoteManagementException : Exception

- (id _Nonnull)initWithErrorMessage:(NSString* _Nonnull)errorMessage errorCode:(NSString* _Nonnull)errorCode;

- (id _Nonnull)initWithErrorMessage:(NSString* _Nonnull)errorMessage;

- (id _Nonnull)init;

- (NSString* _Nonnull)getErrorCode;

@end
