/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Text.djinni

#import <Foundation/Foundation.h>
@class Text;
@class Text;


/** Auto-generated Djinni interface for ::mpsdk::utils::payment_cld::Text_t */
@interface Text : NSObject

- (id _Nonnull)init;

- (id _Nonnull)initWithTypeAndData:(uint8_t)type textData:(NSData* _Nonnull)textData textOffset:(int32_t)textOffset textLength:(int32_t)textLength;

+ (Text* _Nonnull)createWithTypeAndData:(uint8_t)type
                                          textData:(NSData* _Nonnull)textData
                                        textOffset:(int32_t)textOffset
                                        textLength:(int32_t)textLength;

+ (Text* _Nonnull)create;

- (uint8_t)getTextHorizontalPosition;

- (uint8_t)getTextVerticalPosition;

- (uint8_t)getFont;

- (BOOL)isItalic;

- (BOOL)isBold;

- (BOOL)isUnderline;

- (uint8_t)getTextSize;

- (void)setTextSize:(uint8_t)textSize;

- (int32_t)getTextColor;

- (void)setTextColor:(int32_t)textColor;

- (NSString* _Nonnull)getTextValue;

- (void)clear;

@end
