/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from TransactionCredentialInfo.djinni

#import <Foundation/Foundation.h>


/**
 * Auto-generated Djinni interface for ::mpsdk::componentinterface::database::TransactionCredentialInfo_t
 * 
 * Transaction credential information to be saved in database
 * 
 */
@protocol TransactionCredentialInfo

/**
 * 
 * @return unique identifier for a card
 * 
 */
- (NSString* _Nonnull)getCardId;

/**
 * 
 * @return unique identifier for a transaction credential
 * 
 */
- (NSString* _Nonnull)getTransactionCredentialId;

/**
 * 
 * @return Status for a transaction credential status
 * 
 */
- (int32_t)getTransactionCredentialStatus;

/**
 * 
 * @return atc
 * 
 */
- (int32_t)getAtc;

/**
 * 
 * @return time stamp in millis of this transaction credential when added in data
 * 
 */
- (NSString* _Nonnull)getTimeStamp;

/**
 * 
 * @return serialized value of
 * {@link com.mastercard.mpsdk.componentinterface.SingleUseKey_t}
 * 
 */
- (NSData* _Nonnull)getSerializedTransactionCredential;

@end
