/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from BaseRemoteManagementCommand.djinni

#import "mpsdk_remotemanagement/CommandFailureAction.h"
#import "mpsdk_remotemanagement/CommandSuccessAction.h"
#import "mpsdk_remotemanagement/CommandFailureAction.h"
#import "mpsdk_remotemanagement/CommandStatus.h"
#import <Foundation/Foundation.h>
@class CmsDBaseResponse;
@class CmsDRequest;
@class Exception;
@class CmsDBaseResponse;
@class Exception;



#import "mpsdk_remotemanagement/RemoteManagementCommand.h"

/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::commands::impl::BaseRemoteManagementCommand_t
 * 
 * A base command that all others will extend.
 * 
 */
@interface BaseRemoteManagementCommand : RemoteManagementCommand

+ (nonnull NSString *)BASEREQUEST;

/**
 * 
 * Once the command has completed, the response can be deserialized
 * @param serializedResponse the decrypted, serialized response
 * @returns the deserialized Remote Management Command
 * 
 */
- (CmsDBaseResponse* _Nonnull)deserializeResponse:(NSData* _Nonnull)serializedResponse;

/**
 * 
 * The command was successfully processed and does not contain an error code
 * @param response the response
 * 
 */
- (void)onCommandSuccessful:(CmsDBaseResponse* _Nonnull)response;

/**
 * 
 * The command has failed
 * @param action the action to perform
 * @param errorCode the error code
 * @param errorDescription the error description
 * @param exception the exception (if available)
 * 
 */
- (void)onCommandFailed:(CommandFailureAction)action
              errorCode:(NSString* _Nullable)errorCode
       errorDescription:(NSString* _Nullable)errorDescription
              exception:(Exception* _Nonnull)exception;

@end
