/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from CardContactlessPaymentDataJson.djinni

#import <Foundation/Foundation.h>
@class CardAlternateContactlessPaymentDataJson;
@class CardRecordsJson;
@class CardTrackConstructionDataJson;
@class CardTrackConstructionDataJson;
@class CardTrackConstructionDataJson;
@class CardRecordsJson;
@class CardAlternateContactlessPaymentDataJson;


/** Auto-generated Djinni interface for ::mpsdk::card::profile::sdk::CardContactlessPaymentDataJson_t */
@interface CardContactlessPaymentDataJson : NSObject

- (id _Nonnull)init;

@property(nonatomic, readwrite) NSString* _Nonnull cvrMaskAnd;
- (NSString* _Nonnull)cvrMaskAnd;
- (void)setCvrMaskAnd:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull ciacDeclineOnPpms;
- (NSString* _Nonnull)ciacDeclineOnPpms;
- (void)setCiacDeclineOnPpms:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull ciacDecline;
- (NSString* _Nonnull)ciacDecline;
- (void)setCiacDecline:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) CardTrackConstructionDataJson* _Nonnull track2ConstructionData;
- (CardTrackConstructionDataJson* _Nonnull)track2ConstructionData;
- (void)setTrack2ConstructionData:(CardTrackConstructionDataJson* _Nonnull)val;

@property(nonatomic, readwrite) CardTrackConstructionDataJson* _Nonnull track1ConstructionData;
- (CardTrackConstructionDataJson* _Nonnull)track1ConstructionData;
- (void)setTrack1ConstructionData:(CardTrackConstructionDataJson* _Nonnull)val;

@property(nonatomic, readwrite) NSArray<CardRecordsJson*>* _Nonnull records;
- (NSArray<CardRecordsJson*>* _Nonnull)records;
- (void)setRecords:(NSArray<CardRecordsJson*>* _Nonnull)val;

@property(nonatomic, readwrite) CardAlternateContactlessPaymentDataJson* _Nonnull alternateContactlessPaymentData;
- (CardAlternateContactlessPaymentDataJson* _Nonnull)alternateContactlessPaymentData;
- (void)setAlternateContactlessPaymentData:(CardAlternateContactlessPaymentDataJson* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull iccPrivateKeyCrtComponents;
- (NSString* _Nonnull)iccPrivateKeyCrtComponents;
- (void)setIccPrivateKeyCrtComponents:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) BOOL isUsAipMaskingSupported;
- (BOOL)isUsAipMaskingSupported;
- (void)setIsUsAipMaskingSupported:(BOOL)val;

@property(nonatomic, readwrite) BOOL isTransitSupported;
- (BOOL)isTransitSupported;
- (void)setIsTransitSupported:(BOOL)val;

@property(nonatomic, readwrite) NSString* _Nonnull pinIvCvc3Track2;
- (NSString* _Nonnull)pinIvCvc3Track2;
- (void)setPinIvCvc3Track2:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull umdGeneration;
- (NSString* _Nonnull)umdGeneration;
- (void)setUmdGeneration:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull cvmModel;
- (NSString* _Nonnull)cvmModel;
- (void)setCvmModel:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull issuerApplicationData;
- (NSString* _Nonnull)issuerApplicationData;
- (void)setIssuerApplicationData:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) signed int cdol1RelatedDataLength;
- (signed int)cdol1RelatedDataLength;
- (void)setCdol1RelatedDataLength:(signed int)val;

@property(nonatomic, readwrite) NSString* _Nonnull gpoResponse;
- (NSString* _Nonnull)gpoResponse;
- (void)setGpoResponse:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull paymentFci;
- (NSString* _Nonnull)paymentFci;
- (void)setPaymentFci:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull ppseFci;
- (NSString* _Nonnull)ppseFci;
- (void)setPpseFci:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull aid;
- (NSString* _Nonnull)aid;
- (void)setAid:(NSString* _Nonnull)val;

@end
