/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ChangeMobilePinRequest.djinni

#import <Foundation/Foundation.h>
@class ChangeMobilePinRequest;
@class DekEncryptedData;
@class ChangeMobilePinRequest;
@class DekEncryptedData;


/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::json::request::ChangeMobilePinRequest_t
 * 
 * Represents the change mobile pin request for CMS-D.
 * 
 */
@interface ChangeMobilePinRequest : NSObject

- (id _Nonnull)initWithRequestId:(NSString* _Nonnull)requestId tokenUniqueReference:(NSString* _Nonnull)tokenUniqueReference taskId:(NSString* _Nonnull)taskId;

/**
 * 
 * @returns requestId as String
 * 
 */
- (NSString* _Nonnull)getRequestId;

/**
 * 
 * @param requestId requestId as String
 * @returns an Object of ChangeMobilePinRequest_t
 * 
 */
- (ChangeMobilePinRequest* _Nonnull)setRequestId:(NSString* _Nonnull)requestId;

/**
 * 
 * @returns tokenUniqueReference as String
 * 
 */
- (NSString* _Nullable)getTokenUniqueReference;

/**
 * 
 * @param tokenUniqueReference as String
 * @returns an Object of ChangeMobilePinRequest_t
 * 
 */
- (ChangeMobilePinRequest* _Nonnull)setTokenUniqueReference:(NSString* _Nullable)tokenUniqueReference;

/**
 * 
 * @returns current mobile pin as array of utils
 * 
 */
- (NSData* _Nonnull)getCurrentMobilePin;

/**
 * 
 * @param encryptedCurrentPinBlock as array of utils
 * @returns an Object of ChangeMobilePinRequest_t
 * 
 */
- (ChangeMobilePinRequest* _Nonnull)setCurrentMobilePin:(DekEncryptedData* _Nonnull)encryptedCurrentPinBlock;

/**
 * 
 * @returns new mobile pin as array of utils
 * 
 */
- (NSData* _Nonnull)getNewMobilePin;

/**
 * 
 * @param encryptedNewPinBlock as array of utils
 * @returns an Object of ChangeMobilePinRequest_t
 * 
 */
- (ChangeMobilePinRequest* _Nonnull)setNewMobilePin:(DekEncryptedData* _Nonnull)encryptedNewPinBlock;

/**
 * 
 * @returns id for this task as String
 * 
 */
- (NSString* _Nullable)getTaskId;

/**
 * 
 * @param taskId as String
 * @returns an Object of ChangeMobilePinRequest_t
 * 
 */
- (ChangeMobilePinRequest* _Nonnull)setTaskId:(NSString* _Nonnull)taskId;

- (NSString* _Nonnull)toString;

@end
