/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ChangeMobilePinResponse.djinni

#import <Foundation/Foundation.h>
@class ChangeMobilePinResponse;
@class ChangeMobilePinResponse;



#import "mpsdk_remotemanagement/CmsDBaseResponse.h"

/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::json::response::ChangeMobilePinResponse_t
 * 
 * Represents the change mobile pin response for CMS-D.
 * 
 */
@interface ChangeMobilePinResponse : CmsDBaseResponse

- (id _Nonnull)init;

/**
 * 
 * @param result as String
 * 
 */
- (void)setResult:(NSString* _Nonnull)result;

/**
 * 
 * @returns number of tries remaining for mobile pin
 * 
 */
- (int32_t)getMobilePinTriesRemaining;

/**
 * 
 * @param mobilePinTriesRemaining as integer
 * 
 */
- (void)setMobilePinTriesRemaining:(int32_t)mobilePinTriesRemaining;

/**
 * 
 * Returns equivalent
 * ChangeMobilePinResponse_t object
 * from given Json string
 * @param content The Response as Byte Array of the JSON String
 * @returns ChangePinResponse object.
 * 
 */
+ (ChangeMobilePinResponse* _Nonnull)valueOf:(NSData* _Nonnull)content;

- (NSString* _Nonnull)toString;

@end
