/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from CmsDBaseResponse.djinni

#import <Foundation/Foundation.h>
@class CmsDBaseResponse;
@class CmsDBaseResponse;


/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::json::response::CmsDBaseResponse_t
 * 
 * Represents the common protected elements of CMS-D response.
 * 
 */
@interface CmsDBaseResponse : NSObject

- (id _Nonnull)init;

/**
 * 
 * @returns boolean
 * 
 */
- (BOOL)isSuccess;

/**
 * 
 * @returns responseId as String
 * 
 */
- (NSString* _Nonnull)getResponseId;

/**
 * 
 * @param responseId as String
 * 
 */
- (void)setResponseId:(NSString* _Nonnull)responseId;

/**
 * 
 * @returns as String
 * 
 */
- (NSString* _Nonnull)getResponseHost;

/**
 * 
 * @param responseHost as String
 * 
 */
- (void)setResponseHost:(NSString* _Nonnull)responseHost;

/**
 * 
 * @returns as String
 * 
 */
- (NSString* _Nullable)getErrorCode;

/**
 * 
 * @param errorCode as String
 * 
 */
- (void)setErrorCode:(NSString* _Nullable)errorCode;

/**
 * 
 * @returns description of error as String
 * 
 */
- (NSString* _Nullable)getErrorDescription;

/**
 * 
 * @param errorDescription as String
 * 
 */
- (void)setErrorDescription:(NSString* _Nullable)errorDescription;

/**
 * 
 * Returns json string.
 * @returns Json string.
 * 
 */
- (NSString* _Nonnull)toJsonString;

/**
 * 
 * Returns equivalent CmsDBaseResponse_t
 * object from given json string.
 * @param content Json string as Byte Array
 * @returns CmsDBaseResponse_t object.
 * 
 */
+ (CmsDBaseResponse* _Nonnull)valueOf:(NSData* _Nonnull)content;

- (NSString* _Nonnull)toString;

- (NSString* _Nonnull)getResult;

@end
