/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from CmsDNotification.djinni

#import <Foundation/Foundation.h>
@class CmsDNotification;
@class CmsDNotification;


/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::json::encrypted::CmsDNotification_t
 * 
 * Represents the remote notification message from CMS-D.
 * 
 */
@interface CmsDNotification : NSObject

- (id _Nonnull)init;

/**
 * 
 * @returns String-The host that the Mobile Payment App should route requests to. This allows
 * Cms-D to
 * control requests related to a specific conversation to the desired location.
 * 
 */
- (NSString* _Nonnull)getResponseHost;

/**
 * 
 * @param responseHost The host that the Mobile Payment App should route requests to. This
 * allows Cms-D to control requests related to a specific conversation to
 * the desired location.
 * 
 */
- (void)setResponseHost:(NSString* _Nonnull)responseHost;

/**
 * 
 * @returns String-Identifies the Mobile Keys used for this remote management session
 * 
 */
- (NSString* _Nonnull)getMobileKeysetId;

/**
 * 
 * @param mobileKeysetId String-Identifies the Mobile Keys used for this remote management
 * session
 * 
 */
- (void)setMobileKeysetId:(NSString* _Nonnull)mobileKeysetId;

/**
 * 
 * Returns equivalent CmsDNotification_t
 * object from given json string.
 * @param data Json string.
 * @returns CmsDNotification_t object.
 * 
 */
+ (CmsDNotification* _Nonnull)valueOf:(NSString* _Nonnull)data;

/**
 * 
 * Returns json string.
 * @returns Json string.
 * 
 */
- (NSString* _Nonnull)toJsonString;

/**
 * 
 * @returns String-the protected RemoteManagementSessionData object.
 * The plaintext data is prepended with a random 16-byte value before it is protected by the
 * Mobile Transport Key using CBC mode padded with '80' followed by '00' utils until the end
 * of the block. The MAC is then computed over the output, which is appended to the end
 * 
 */
- (NSString* _Nonnull)getEncryptedData;

/**
 * 
 * @param encryptedData as String
 * 
 */
- (void)setEncryptedData:(NSString* _Nonnull)encryptedData;

- (NSString* _Nonnull)toString;

@end
