/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from CmsDResponse.djinni

#import <Foundation/Foundation.h>
@class CmsDResponse;
@class CmsDResponse;


/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::json::encrypted::CmsDResponse_t
 * 
 * Represents top level JSON that remote management library receive from Cms-D
 * 
 */
@interface CmsDResponse : NSObject

- (id _Nonnull)init;

/**
 * 
 * Returns CmsDResponse_t
 * @param data Json string as byte[]
 * @returns Instance of CmsDResponse_t
 * 
 */
+ (CmsDResponse* _Nonnull)valueOf:(NSData* _Nonnull)data;

- (NSString* _Nullable)getErrorCode;

- (void)setErrorCode:(NSString* _Nullable)errorCode;

- (NSString* _Nullable)getErrorDescription;

- (void)setErrorDescription:(NSString* _Nullable)errorDescription;

- (NSString* _Nonnull)getEncryptedData;

- (void)setEncryptedData:(NSString* _Nonnull)encryptedData;

/**
 * 
 * Returns equivalent Json string.
 * @returns Json string
 * 
 */
- (NSString* _Nonnull)toJsonString;

/**
 * 
 * Returns true of if error is presents in response
 * 
 */
- (BOOL)isSuccess;

- (NSString* _Nonnull)toString;

@end
