/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from CmsDRequest.djinni

#import <Foundation/Foundation.h>
@class CmsDRequest;
@class CmsDRequest;


/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::json::encrypted::CmsDRequest_t
 * 
 * Represents top level JSON that remote management library sends to Cms-D
 * 
 */
@interface CmsDRequest : NSObject

- (id _Nonnull)init;

/**
 * 
 * Returns equivalent CmsDRequest_t
 * object from given json string.
 * @param jsonString Json string.
 * @returns CmsDRequest_t object.
 * 
 */
+ (CmsDRequest* _Nonnull)valueOf:(NSString* _Nonnull)jsonString;

/**
 * 
 * Returns Mobile key set id
 * 
 */
- (NSString* _Nonnull)getMobileKeysetId;

/**
 * 
 * Assign mobile key set id
 * 
 */
- (CmsDRequest* _Nonnull)setMobileKeysetId:(NSString* _Nonnull)mobileKeysetId;

/**
 * 
 * Returns authentication code
 * 
 */
- (NSData* _Nonnull)getAuthenticationCode;

/**
 * 
 * Assign authentication code
 * 
 */
- (CmsDRequest* _Nonnull)setAuthenticationCode:(NSData* _Nonnull)authenticationCode;

/**
 * 
 * Returns protected data
 * 
 */
- (NSString* _Nonnull)getEncryptedData;

/**
 * 
 * Assign protected data
 * 
 */
- (CmsDRequest* _Nonnull)setEncryptedData:(NSString* _Nonnull)encryptedData;

- (NSString* _Nonnull)toString;

@end
