/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from CommandStatus.djinni

#import <Foundation/Foundation.h>

/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::queue::CommandStatus_t
 * 
 * Represents the local status of a command.
 * 
 */
typedef NS_ENUM(NSInteger, CommandStatus)
{
    /**
     * 
     * Request is in the queue
     * 
     */
    CommandStatus_PENDING,
    /**
     * 
     * Request is currently being processed
     * 
     */
    CommandStatus_EXECUTING,
    /**
     * 
     * Request has been sent, however, the server must be queried in order to determine if it was
     * successful or not as more data is required (e.g. Change PIN)
     * 
     */
    CommandStatus_SENT,
    /**
     * 
     * Request was successful
     * 
     */
    CommandStatus_SUCCESS,
    /**
     * 
     * The request failed
     * 
     */
    CommandStatus_FAILED,
    /**
     * 
     * The request was canceled
     * 
     */
    CommandStatus_CANCELED,
    /**
     * 
     * The request status could not be determined
     * 
     */
    CommandStatus_UNKNOWN,
    /**
     * 
     * Another command is already in process
     * 
     */
    CommandStatus_ALREADY_IN_PROCESS,
    /**
     * 
     * This was a duplicate command found in the queue and never executed
     * 
     */
    CommandStatus_DUPLICATE,
};
