/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ContactlessPaymentDataV1Json.djinni

#import <Foundation/Foundation.h>
@class IccPrivateKeyCrtComponentsJson;
@class AlternateContactlessPaymentDataJson;
@class RecordsJson;
@class RecordsJson;
@class AlternateContactlessPaymentDataJson;
@class IccPrivateKeyCrtComponentsJson;


/**
 * Auto-generated Djinni interface for ::mpsdk::card::profile::v1::ContactlessPaymentDataV1Json_t
 * 
 * Represents the contactless payment data in card profile of mdes.
 * 
 */
@interface ContactlessPaymentDataV1Json : NSObject

- (id _Nonnull)init;

@property(nonatomic, readwrite) NSArray<RecordsJson*>* _Nonnull records;
- (NSArray<RecordsJson*>* _Nonnull)records;
- (void)setRecords:(NSArray<RecordsJson*>* _Nonnull)val;

@property(nonatomic, readwrite) AlternateContactlessPaymentDataJson* _Nonnull alternateContactlessPaymentData;
- (AlternateContactlessPaymentDataJson* _Nonnull)alternateContactlessPaymentData;
- (void)setAlternateContactlessPaymentData:(AlternateContactlessPaymentDataJson* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull ciacDeclineOnPpms;
- (NSString* _Nonnull)ciacDeclineOnPpms;
- (void)setCiacDeclineOnPpms:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull pinIvCvc3Track2;
- (NSString* _Nonnull)pinIvCvc3Track2;
- (void)setPinIvCvc3Track2:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) IccPrivateKeyCrtComponentsJson* _Nonnull iccPrivateKeyCrtComponents;
- (IccPrivateKeyCrtComponentsJson* _Nonnull)iccPrivateKeyCrtComponents;
- (void)setIccPrivateKeyCrtComponents:(IccPrivateKeyCrtComponentsJson* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull issuerApplicationData;
- (NSString* _Nonnull)issuerApplicationData;
- (void)setIssuerApplicationData:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull cvrMaskAnd;
- (NSString* _Nonnull)cvrMaskAnd;
- (void)setCvrMaskAnd:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull ciacDecline;
- (NSString* _Nonnull)ciacDecline;
- (void)setCiacDecline:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull cdol1RelatedDataLength;
- (NSString* _Nonnull)cdol1RelatedDataLength;
- (void)setCdol1RelatedDataLength:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull gpoResponse;
- (NSString* _Nonnull)gpoResponse;
- (void)setGpoResponse:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull paymentFci;
- (NSString* _Nonnull)paymentFci;
- (void)setPaymentFci:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull ppseFci;
- (NSString* _Nonnull)ppseFci;
- (void)setPpseFci:(NSString* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull aid;
- (NSString* _Nonnull)aid;
- (void)setAid:(NSString* _Nonnull)val;

@end
