/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DeleteTokenRequest.djinni

#import <Foundation/Foundation.h>
@protocol SingleUseKeyStatus;
@class DeleteTokenRequest;
@class DeleteTokenRequest;
@protocol SingleUseKeyStatus;


/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::json::request::DeleteTokenRequest_t
 * 
 * Encapsulate the data which will be needed to process request to delete a Token Credential.
 * 
 */
@interface DeleteTokenRequest : NSObject

- (id _Nonnull)initWithRequestId:(NSString* _Nonnull)requestId tokenUniqueReference:(NSString* _Nonnull)tokenUniqueReference transactionCredentialStatuses:(NSArray<id<SingleUseKeyStatus>>* _Nonnull)transactionCredentialStatuses;

/**
 * 
 * @returns resquest id as String
 * 
 */
- (NSString* _Nonnull)getRequestId;

/**
 * 
 * @param requestId as String
 * @returns an object of DeleteTokenRequest_t
 * 
 */
- (DeleteTokenRequest* _Nonnull)setRequestId:(NSString* _Nonnull)requestId;

/**
 * 
 * @returns tokenUniqueReference as String
 * 
 */
- (NSString* _Nullable)getTokenUniqueReference;

/**
 * 
 * @param tokenUniqueReference as String
 * @returns an object of DeleteTokenRequest_t
 * 
 */
- (DeleteTokenRequest* _Nonnull)setTokenUniqueReference:(NSString* _Nullable)tokenUniqueReference;

/**
 * 
 * @returns byte array of SingleUseKeyStatus_t
 * 
 */
- (NSArray<id<SingleUseKeyStatus>>* _Nonnull)getTransactionCredentialsStatus;

/**
 * 
 * @param transactionCredentialsStatus as byte array of SingleUseKeyStatus_t
 * @returns an object of DeleteTokenRequest_t
 * 
 */
- (DeleteTokenRequest* _Nonnull)setTransactionCredentialsStatus:(NSArray<id<SingleUseKeyStatus>>* _Nonnull)transactionCredentialsStatus;

- (NSString* _Nonnull)toString;

@end
