/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DigitizedCardProfileV1Json.djinni

#import "mpsdk_componentinterface/ProfileVersion.h"
#import "mpsdk_componentinterface/ProfileVersion.h"
#import <Foundation/Foundation.h>
@class DigitizedCardProfileV1Json;
@class MppLiteModuleV1Json;
@class BusinessLogicModuleV1Json;
@class BusinessLogicModuleV1Json;
@class MppLiteModuleV1Json;
@class DigitizedCardProfileV1Json;



#import "mpsdk_remotemanagement/DigitizedCardProfile.h"

/**
 * Auto-generated Djinni interface for ::mpsdk::card::profile::v1::DigitizedCardProfileV1Json_t
 * 
 * Represents the digitized card profile of mdes.
 * It is also providing the conversion of mdes profile structure into core card profile structure.
 * 
 */
@interface DigitizedCardProfileV1Json : NSObject<DigitizedCardProfile>

- (id _Nonnull)init;

@property(nonatomic, readwrite) BusinessLogicModuleV1Json* _Nonnull businessLogicModule;
- (BusinessLogicModuleV1Json* _Nonnull)businessLogicModule;
- (void)setBusinessLogicModule:(BusinessLogicModuleV1Json* _Nonnull)val;

@property(nonatomic, readwrite) MppLiteModuleV1Json* _Nonnull mppLiteModule;
- (MppLiteModuleV1Json* _Nonnull)mppLiteModule;
- (void)setMppLiteModule:(MppLiteModuleV1Json* _Nonnull)val;

@property(nonatomic, readwrite) signed int maximumPinTry;
- (signed int)maximumPinTry;
- (void)setMaximumPinTry:(signed int)val;

@property(nonatomic, readwrite) NSString* _Nonnull digitizedCardId;
- (NSString* _Nonnull)digitizedCardId;
- (void)setDigitizedCardId:(NSString* _Nonnull)val;

+ (DigitizedCardProfileV1Json* _Nonnull)valueOf:(NSData* _Nonnull)data;

- (ProfileVersion)getProfileVersion;

@end
