/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DigitizedCardProfileV2Json.djinni

#import "mpsdk_componentinterface/ProfileVersion.h"
#import "mpsdk_componentinterface/ProfileVersion.h"
#import <Foundation/Foundation.h>
@class DigitizedCardProfileV2Json;
@class WalletRelatedDataV2Json;
@class MchipCardProfileV2Json;
@class MchipCardProfileV2Json;
@class WalletRelatedDataV2Json;
@class DigitizedCardProfileV2Json;



#import "mpsdk_remotemanagement/DigitizedCardProfile.h"

/** Auto-generated Djinni interface for ::mpsdk::card::profile::v2::DigitizedCardProfileV2Json_t */
@interface DigitizedCardProfileV2Json : NSObject<DigitizedCardProfile>

- (id _Nonnull)init;

@property(nonatomic, readwrite) MchipCardProfileV2Json* _Nonnull mchipCardProfile;
- (MchipCardProfileV2Json* _Nonnull)mchipCardProfile;
- (void)setMchipCardProfile:(MchipCardProfileV2Json* _Nonnull)val;

@property(nonatomic, readwrite) WalletRelatedDataV2Json* _Nonnull walletRelatedData;
- (WalletRelatedDataV2Json* _Nonnull)walletRelatedData;
- (void)setWalletRelatedData:(WalletRelatedDataV2Json* _Nonnull)val;

@property(nonatomic, readwrite) NSString* _Nonnull version;
- (NSString* _Nonnull)version;
- (void)setVersion:(NSString* _Nonnull)val;

+ (DigitizedCardProfileV2Json* _Nonnull)valueOf:(NSData* _Nonnull)data;

- (ProfileVersion)getProfileVersion;

@end
