/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ErrorCode.djinni

#import <Foundation/Foundation.h>

/**
 * 
 * Error code for Cms-D to Mpa or Mpa to Cms-D counter mismatch.
 * 
 */
extern NSString * __nonnull const ErrorCode_COUNTER_MISMATCH;
/**
 * 
 * Error code for any failure in cryptographic operations.
 * 
 */
extern NSString * __nonnull const ErrorCode_SDK_CRYPTOGRAPHY_ERROR;
/**
 * 
 * Error code for the input parameter to command are invalid e.g. null.
 * 
 */
extern NSString * __nonnull const ErrorCode_SDK_INVALID_INPUTS;
/**
 * 
 * Error code for Http communication failure
 * 
 */
extern NSString * __nonnull const ErrorCode_SDK_HTTP_ERROR;
/**
 * 
 * The command was canceled
 * 
 */
extern NSString * __nonnull const ErrorCode_COMMAND_CANCELED;
/**
 * 
 * The Remote Management module does not have access to the mobile keys
 * 
 */
extern NSString * __nonnull const ErrorCode_MOBILE_KEYS_MISSING;
/**
 * 
 * No transaction credentials were received from CMS-D
 * 
 */
extern NSString * __nonnull const ErrorCode_MISSING_TRANSACTION_CREDENTIALS;
/**
 * 
 * Change PIN request contained incorrect current PIN
 * 
 */
extern NSString * __nonnull const ErrorCode_INCORRECT_MOBILE_PIN;
/**
 * 
 * No network connectivity is available
 * 
 */
extern NSString * __nonnull const ErrorCode_NETWORK_ERROR;
/**
 * 
 * No Registration data is provided i.e., CMS url or mobile keys.
 * 
 */
extern NSString * __nonnull const ErrorCode_REGISTRATION_DATA_NOT_AVAILABLE;
/**
 * 
 * HTTP Service not available (HTTP error code 503)
 * 
 */
extern NSString * __nonnull const ErrorCode_SERVICE_UNAVAILABLE_503;
/**
 * 
 * Error Code if notification arrives and any other request is already being processed
 * 
 */
extern NSString * __nonnull const ErrorCode_ALREADY_IN_PROCESS;
/**
 * 
 * Received different keySetId in Remote notification than the SDK has in registration response
 * 
 */
extern NSString * __nonnull const ErrorCode_MOBILE_KEYSET_MISMATCH;

/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::ErrorCode_t
 * 
 * List of error code for remote management library
 * 
 */
@interface ErrorCode : NSObject

@end
