/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from GetTaskStatusRequest.djinni

#import <Foundation/Foundation.h>
@class GetTaskStatusRequest;
@class GetTaskStatusRequest;


/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::json::request::GetTaskStatusRequest_t
 * 
 * Represents Get task status request to Cms-D.
 * 
 */
@interface GetTaskStatusRequest : NSObject

- (id _Nonnull)initWithRequestId:(NSString* _Nonnull)requestId taskId:(NSString* _Nonnull)taskId;

/**
 * 
 * @returns requestId as String
 * 
 */
- (NSString* _Nonnull)getRequestId;

/**
 * 
 * @param requestId as String
 * @returns an object of GetTaskStatusRequest_t
 * 
 */
- (GetTaskStatusRequest* _Nonnull)setRequestId:(NSString* _Nonnull)requestId;

/**
 * 
 * @returns taskId as String
 * 
 */
- (NSString* _Nullable)getTaskId;

/**
 * 
 * @param taskId as String
 * @returns an object of GetTaskStatusRequest_t
 * 
 */
- (GetTaskStatusRequest* _Nonnull)setTaskId:(NSString* _Nonnull)taskId;

- (NSString* _Nonnull)toString;

@end
