/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from McbpErrorCode.djinni

#import <Foundation/Foundation.h>

/**
 * Auto-generated Djinni interface for ::mpsdk::exceptions::McbpErrorCode_t
 * 
 * Generic MCBP exception error codes list.
 * 
 */
typedef NS_ENUM(NSInteger, McbpErrorCode)
{
    /**
     * 
     * Unknown error occurred
     * 
     */
    McbpErrorCode_GENERAL_ERROR = 1101,
    /**
     * 
     * Cryptographic error occurred
     * 
     */
    McbpErrorCode_CRYPTO_ERROR = 1102,
    /**
     * 
     * Error occurred while executing operation on CMS-D
     * 
     */
    McbpErrorCode_SERVER_ERROR = 1103,
    /**
     * 
     * Local protected database error occurred
     * 
     */
    McbpErrorCode_DE_ERROR = 1104,
    /**
     * 
     * Unknown error occurred while communication
     * 
     */
    McbpErrorCode_UNKNOWN_HTTP_ERROR_CODE = 1105,
    /**
     * 
     * Error occurred at SSL level while communication
     * 
     */
    McbpErrorCode_SSL_ERROR_CODE = 1106,
    /**
     * 
     * Http timeout occurred
     * 
     */
    McbpErrorCode_HTTP_TIMEOUT_OCCURRED = 1107,
    /**
     * 
     * Failed to retrieve public key certificate.
     * 
     */
    McbpErrorCode_FAILED_TO_RETRIEVE_CERTIFICATE = 1108,
    /**
     * 
     * Card is already provision
     * 
     */
    McbpErrorCode_CARD_ALREADY_PROVISION = 1109,
    /**
     * 
     * User already register with CMS-D
     * 
     */
    McbpErrorCode_USER_ALREADY_REGISTER = 1110,
};
