/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MchipCardProfileV2Json.djinni

#import <Foundation/Foundation.h>
@class CommonDataV2Json;
@class ContactlessPaymentDataV2Json;
@class DsrpDataV2Json;
@class DsrpDataV2Json;
@class ContactlessPaymentDataV2Json;
@class CommonDataV2Json;


/** Auto-generated Djinni interface for ::mpsdk::card::profile::v2::MchipCardProfileV2Json_t */
@interface MchipCardProfileV2Json : NSObject

- (id _Nonnull)init;

@property(nonatomic, readwrite) DsrpDataV2Json* _Nonnull dsrpData;
- (DsrpDataV2Json* _Nonnull)dsrpData;
- (void)setDsrpData:(DsrpDataV2Json* _Nonnull)val;

@property(nonatomic, readwrite) ContactlessPaymentDataV2Json* _Nonnull contactlessPaymentData;
- (ContactlessPaymentDataV2Json* _Nonnull)contactlessPaymentData;
- (void)setContactlessPaymentData:(ContactlessPaymentDataV2Json* _Nonnull)val;

@property(nonatomic, readwrite) CommonDataV2Json* _Nonnull commonData;
- (CommonDataV2Json* _Nonnull)commonData;
- (void)setCommonData:(CommonDataV2Json* _Nonnull)val;

@end
