/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MChipCvmIssuerOptionsV1Json.djinni

#import <Foundation/Foundation.h>


/**
 * Auto-generated Djinni interface for ::mpsdk::card::profile::v1::MChipCvmIssuerOptionsV1Json_t
 * 
 * Represents the mchip issuer options in card profile of mdes.
 * 
 */
@interface MChipCvmIssuerOptionsV1Json : NSObject

- (id _Nonnull)init;

@property(nonatomic, readwrite) BOOL pinPreEntryAllowed;
- (BOOL)pinPreEntryAllowed;
- (void)setPinPreEntryAllowed:(BOOL)val;

@property(nonatomic, readwrite) BOOL pinAutomaticallyResetByApplication;
- (BOOL)pinAutomaticallyResetByApplication;
- (void)setPinAutomaticallyResetByApplication:(BOOL)val;

@property(nonatomic, readwrite) BOOL pinAlwaysRequiredIfCurrencyProvided;
- (BOOL)pinAlwaysRequiredIfCurrencyProvided;
- (void)setPinAlwaysRequiredIfCurrencyProvided:(BOOL)val;

@property(nonatomic, readwrite) BOOL pinAlwaysRequiredIfCurrencyNotProvided;
- (BOOL)pinAlwaysRequiredIfCurrencyNotProvided;
- (void)setPinAlwaysRequiredIfCurrencyNotProvided:(BOOL)val;

@property(nonatomic, readwrite) BOOL ackPreEntryAllowed;
- (BOOL)ackPreEntryAllowed;
- (void)setAckPreEntryAllowed:(BOOL)val;

@property(nonatomic, readwrite) BOOL ackAutomaticallyResetByApplication;
- (BOOL)ackAutomaticallyResetByApplication;
- (void)setAckAutomaticallyResetByApplication:(BOOL)val;

@property(nonatomic, readwrite) BOOL ackAlwaysRequiredIfCurrencyProvided;
- (BOOL)ackAlwaysRequiredIfCurrencyProvided;
- (void)setAckAlwaysRequiredIfCurrencyProvided:(BOOL)val;

@property(nonatomic, readwrite) BOOL ackAlwaysRequiredIfCurrencyNotProvided;
- (BOOL)ackAlwaysRequiredIfCurrencyNotProvided;
- (void)setAckAlwaysRequiredIfCurrencyNotProvided:(BOOL)val;

@end
