/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from MppLiteModuleV1Json.djinni

#import <Foundation/Foundation.h>
@class CardRiskManagementDataV1Json;
@class ContactlessPaymentDataV1Json;
@class RemotePaymentDataV1Json;
@class RemotePaymentDataV1Json;
@class ContactlessPaymentDataV1Json;
@class CardRiskManagementDataV1Json;


/**
 * Auto-generated Djinni interface for ::mpsdk::card::profile::v1::MppLiteModuleV1Json_t
 * 
 * Represents the mpplite module in card profile of mdes.
 * 
 */
@interface MppLiteModuleV1Json : NSObject

- (id _Nonnull)init;

@property(nonatomic, readwrite) RemotePaymentDataV1Json* _Nonnull remotePaymentData;
- (RemotePaymentDataV1Json* _Nonnull)remotePaymentData;
- (void)setRemotePaymentData:(RemotePaymentDataV1Json* _Nonnull)val;

@property(nonatomic, readwrite) ContactlessPaymentDataV1Json* _Nonnull contactlessPaymentData;
- (ContactlessPaymentDataV1Json* _Nonnull)contactlessPaymentData;
- (void)setContactlessPaymentData:(ContactlessPaymentDataV1Json* _Nonnull)val;

@property(nonatomic, readwrite) CardRiskManagementDataV1Json* _Nonnull cardRiskManagementData;
- (CardRiskManagementDataV1Json* _Nonnull)cardRiskManagementData;
- (void)setCardRiskManagementData:(CardRiskManagementDataV1Json* _Nonnull)val;

@end
