/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from NotifyProvisionRequest.djinni

#import <Foundation/Foundation.h>
@class NotifyProvisionRequest;
@class NotifyProvisionRequest;


/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::json::request::NotifyProvisionRequest_t
 * 
 * Represents the notifying token provision result to CMS-D.
 * 
 */
@interface NotifyProvisionRequest : NSObject

- (id _Nonnull)initWithTokenUniqueReference:(NSString* _Nonnull)tokenUniqueReference requestId:(NSString* _Nonnull)requestId errorCode:(NSString* _Nonnull)errorCode errorDescription:(NSString* _Nonnull)errorDescription result:(NSString* _Nonnull)result;

/**
 * 
 * @returns String tokenUniqueReference
 * 
 */
- (NSString* _Nullable)getTokenUniqueReference;

- (NotifyProvisionRequest* _Nonnull)setTokenUniqueReference:(NSString* _Nullable)tokenUniqueReference;

/**
 * 
 * @returns String SUCCESS in case of Provisioning completed successfully
 * and the target device/application is ready. ERROR An error occurred during provisioning.
 * 
 */
- (NSString* _Nonnull)getResult;

- (NotifyProvisionRequest* _Nonnull)setResult:(NSString* _Nonnull)result;

- (NSString* _Nullable)getErrorCode;

- (NotifyProvisionRequest* _Nonnull)setErrorCode:(NSString* _Nullable)errorCode;

/**
 * 
 * @returns String Error description of the reason the provisioning failed.
 * 
 */
- (NSString* _Nullable)getErrorDescription;

- (NotifyProvisionRequest* _Nonnull)setErrorDescription:(NSString* _Nullable)errorDescription;

/**
 * 
 * @returns String requestId
 * 
 */
- (NSString* _Nonnull)getRequestId;

- (NotifyProvisionRequest* _Nonnull)setRequestId:(NSString* _Nonnull)requestId;

- (NSString* _Nonnull)toString;

@end
