/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ProvisionResponse.djinni

#import <Foundation/Foundation.h>
@protocol DigitizedCardProfile;
@class ProvisionResponse;
@class ProvisionResponse;
@protocol DigitizedCardProfile;



#import "mpsdk_remotemanagement/CmsDBaseResponse.h"

/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::json::response::ProvisionResponse_t
 * 
 * Represents the token provision response for CMS-D.
 * 
 */
@interface ProvisionResponse : CmsDBaseResponse

- (id _Nonnull)init;

/**
 * 
 * @returns representation of a card profile
 * 
 */
- (id<DigitizedCardProfile> _Nonnull)getCardProfile;

/**
 * 
 * @param cardProfile representation of a card profile
 * 
 */
- (void)setCardProfile:(id<DigitizedCardProfile> _Nonnull)cardProfile;

/**
 * 
 * @returns iccKek as String
 * 
 */
- (NSString* _Nullable)getIccKek;

/**
 * 
 * @param iccKek as String
 * 
 */
- (void)setIccKek:(NSString* _Nullable)iccKek;

/**
 * 
 * Returns equivalent ProvisionResponse_t
 * object from given json string.
 * @param content Json string as Byte Array
 * @returns TokenProvisionResponse object.
 * 
 */
+ (ProvisionResponse* _Nonnull)valueOf:(NSData* _Nonnull)content;

- (NSString* _Nonnull)toString;

@end
