/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ProvisionRequest.djinni

#import <Foundation/Foundation.h>
@class ProvisionRequest;
@class ProvisionRequest;


/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::json::request::ProvisionRequest_t
 * 
 * Represents the token provision request to Cms-D.
 * 
 */
@interface ProvisionRequest : NSObject

- (id _Nonnull)initWithTokenUniqueReference:(NSString* _Nonnull)tokenUniqueReference requestId:(NSString* _Nonnull)requestId;

/**
 * 
 * @returns tokenUniqueReference as String
 * 
 */
- (NSString* _Nullable)getTokenUniqueReference;

/**
 * 
 * @param tokenUniqueReference as String
 * @returns an object of ProvisionRequest_t
 * 
 */
- (ProvisionRequest* _Nonnull)setTokenUniqueReference:(NSString* _Nullable)tokenUniqueReference;

/**
 * 
 * @returns requestId as String
 * 
 */
- (NSString* _Nonnull)getRequestId;

/**
 * 
 * @param requestId as String
 * @returns an object of ProvisionRequest_t
 * 
 */
- (ProvisionRequest* _Nonnull)setRequestId:(NSString* _Nonnull)requestId;

- (NSString* _Nonnull)toString;

@end
