/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from SessionContext.djinni

#import <Foundation/Foundation.h>
@protocol SessionData;
@protocol SessionData;


/**
 * Auto-generated Djinni interface for ::mpsdk::remotemanagement::session::SessionContext_t
 * 
 * Maintains the current context of the session
 * 
 */
@interface SessionContext : NSObject

- (id _Nonnull)initWithSessionData:(id<SessionData> _Nonnull)sessionData responseHost:(NSString* _Nonnull)responseHost;

/**
 * 
 * Indicates if the current session is still valid at this point in time
 * @returns true if the session is valid, false if it is not
 * 
 */
- (BOOL)isValidSession;

/**
 * 
 * set flag as used
 * 
 */
- (void)markSessionAsUsed;

- (id<SessionData> _Nonnull)getSessionData;

- (NSString* _Nonnull)getResponseHost;

- (int32_t)getCmsDToMpaRequestCounter;

- (void)setCmsDToMpaRequestCounter:(int32_t)counter;

- (int32_t)getMpaToCmsDRequestCounter;

- (void)increaseMpaToCmsDRequestCounter;

@end
