/**
 *  Copyright (c) 2018, MasterCard International Incorporated and/or its
 *  affiliates. All rights reserved.
 *
 *  The contents of this file may only be used subject to the MasterCard
 *  Mobile Payment SDK for MCBP and/or MasterCard Mobile MPP UI SDK
 *  Materials License.
 *
 *  Please refer to the file LICENSE.TXT for full details.
 *
 *  TO THE EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 *  WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NON INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 *  MASTERCARD OR ITS AFFILIATES BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 **/

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from TransactionCredentialData.djinni

#import <Foundation/Foundation.h>
@class TransactionCredentialData;
@class TransactionCredentialData;


/** Auto-generated Djinni interface for ::mpsdk::remotemanagement::json::credentials::TransactionCredentialData_t */
@interface TransactionCredentialData : NSObject

- (id _Nonnull)init;

- (int32_t)getAtc;

- (void)setAtc:(int32_t)atc;

- (NSData* _Nullable)getIdn;

- (void)setIdn:(NSData* _Nullable)idn;

- (NSData* _Nullable)getContactlessMdSessionKey;

- (void)setContactlessMdSessionKey:(NSData* _Nullable)contactlessMdSessionKey;

- (NSData* _Nullable)getContactlessUmdSingleUseKey;

- (void)setContactlessUmdSingleUseKey:(NSData* _Nullable)contactlessUmdSingleUseKey;

- (NSData* _Nullable)getDsrpMdSessionKey;

- (void)setDsrpMdSessionKey:(NSData* _Nullable)dsrpMdSessionKey;

- (NSData* _Nullable)getDsrpUmdSingleUseKey;

- (void)setDsrpUmdSingleUseKey:(NSData* _Nullable)dsrpUmdSingleUseKey;

- (NSData* _Nullable)getContactlessUmdSessionKey;

- (void)setContactlessUmdSessionKey:(NSData* _Nullable)contactlessUmdSessionKey;

- (NSData* _Nullable)getDsrpUmdSessionKey;

- (void)setDsrpUmdSessionKey:(NSData* _Nullable)dsrpUmdSessionKey;

+ (TransactionCredentialData* _Nonnull)valueOf:(NSString* _Nonnull)jsonContent;

- (NSString* _Nonnull)toString;

@end
